routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\serveur\CommandeController;
use App\Http\Controllers\Visiteur\CategorieController;
use App\Http\Controllers\Serveur\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route("home");
});
Route::get("/home", [CategorieController::class, "index"])->name('home');
Route::get("/plats/{categorie}", [CategorieController::class, "plats"])->name("plats_Categorie");


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
Route::middleware("auth")->group(function(){
    Route::get("dashboard", [DashboardController::class, "index"])->name("dashboard");
    Route::get("dashboard/categorie/{categorie}", [DashboardController::class, "show"])->name("dashboard.categorie.show");
    Route::get("serveur/commande/creer", [CommandeController::class, "creer"])->name("serveur.commande.creer");
    // Route::get("serveur/commande/{commande}/edit", [CommandeController::class, "edit"])->name("serveur.commande.edit");
 Route::get("serveur/commande/terminer/{commande?}", [CommandeController::class, "terminer"])->name("commande.terminer");
    // Route::post("serveur/commande/{commande}/update", [CommandeController::class, "update"])->name("serveur.commande.update");

    Route::resource("seveur/commande", CommandeController::class);

    Route::post("serveur/plat/add", [CommandeController::class, "add_plat"])->name("serveur.commande.add_plat");
    Route::get("serveur/commande/{commande}/{etat}", [CommandeController::class, "changerEtat"])->name("serveur.commande.changer_etat");

});

resources/views/templates/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('titre')</title>
    <!-- <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}"> -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <style>
        img{
           width: 200px; /* You can set the dimensions to whatever you want */
            height: 200px;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mon Resto</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Commandes</a>
        </li>
        <li class="nav-item dropdown" id="defaultNavbar1">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            Paramétrage
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Catégories</a></li>
            <li><a class="dropdown-item" href="#">Plats</a></li>
            <li><a class="dropdown-item" href="#">Serveurs</a></li>
       </ul>
        </li>
      
      </ul>
      
    </div>
  </div>
</nav>
    <div class="container mt-3 mb-5">
        @yield('contenu')
    </div>
<!-- <script src="{{ asset('js/jquery-3.6.4.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>
</html>

resources/views/templates/serveur.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('titre')</title>
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <style>
      .small-img{
        
           width: 60px; /* You can set the dimensions to whatever you want */
            height: 60px;
            object-fit: cover;
            display: block;
     
      }
       .medium-img{
         width: 150px; /* You can set the dimensions to whatever you want */
            height: 150px;
            object-fit: cover;
            display: block;
            margin:auto;
       }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary d-flex justyfy-content-between">
  <div class="container-fluid">
    <div class="card">
      <a class="navbar-brand" href="{{route('home')}}">Mon Resto <br>
                @auth
              <span class="fs-6"> Serveur : {{Auth::user()->name}}</span> 
                @endauth
          </a>
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
   </div>
    
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 ">
        <li class="nav-item">
          <a  aria-current="page" href="{{route('dashboard')}}" class=" nav-link {{(Route::is('dashboard'))? 'active':''}}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a  href="{{route('commande.index')}}" class="nav-link {{(Route::is('commande.index'))? 'active':''}}">Commandes</a>
        </li>
      
      </ul>
      <div>
        @if(!Session::has("commande"))
          <a href="{{route('serveur.commande.creer')}}" class="btn btn-primary">Nouvelle commande</a>
        @else
          @php
            $commande=Session::get("commande");
            $nombrePlats=$commande->plats()->count();
          @endphp
          <span>Commande créée</span>
          <a href="{{route('commande.edit', $commande->id)}}" class="btn btn-success">Editer</a>
          <a href="{{route('commande.terminer')}}" class="btn btn-primary">Terminer ({{ $nombrePlats }})</a>
        @endif
      </div>
    </div>
  </div>
</nav>
    <div class="container mt-3 mb-5">
        @yield('content')
    </div>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
</body>
</html>

resources/views/templates/visiteur.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('titre')</title>
    <!-- <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}"> -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        img{
           width: 200px; 
            height: 200px;
            object-fit: cover;
        }
  
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary ">
  <div class="container-fluid ">
    <a class="navbar-brand" href="{{route('home')}}">Mon Resto</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{route('home')}}">Menu</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">Présentation</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Localisation et horaires</a>
        </li>
       
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{{route('login')}}">Login</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>
    <div class="container mt-3 mb-5">
        @yield('contenu')
    </div>
<!-- <script src="{{ asset('js/jquery-3.6.4.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>
</html>